### ISSUE TITLE
mixed encodings error when reading file lists

### ISSUE THREAD

**Issue by tonibony** [Jwink3101/syncrclone#24]
I got the following error (and similar) while syncrclone was reading the file lists (initially the lists generated by rclone and then the saved lists from previous run):

`ERROR: 'charmap' codec can't decode byte 0x98 in position 63910: character maps to <undefined>`

I investigated the problem and found the reason - it's combination of the following:

- Synced files have non-ASCII characters in their names (cyrillic in my case).
- The platform (Windows, in my case) "uses legacy encodings for the system encoding (the ANSI Code Page). Python uses it for the default encoding of text files" (I am citing Python's documentation [Using Python on Windows](https://docs.python.org/3/using/windows.html)).
- Syncrclone opens text files without specifying file's encoding (which should be utf-8) and that's somewhat problematic in current versions of Python - see [PEP 597 – Add optional EncodingWarning](https://peps.python.org/pep-0597/).

These findings led me to a successful workaround of the problem - I forced Python in [UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode) by setting the environment variable `PYTHONUTF8=1`.

Now, I know that syncrclone can be patched to fix this problem, by adding the optional parameter `encoding="utf-8"` to the relevant `open(...)` calls (because I tried that too). But I'm not sure if that's the right thing to do. It looks like the problem will be solved in the upcoming Python versions (10.15, as planned) - see [PEP 686 – Make UTF-8 mode default](https://peps.python.org/pep-0686/).

**Comment by tonibony** [comment]
Hmmm, the reasons for #16 might be something similar ...

**Comment by Jwink3101** [comment]
Thanks for bringing this to my attention. I seem to recall, but need to confirm, that rclone _always_ uses UTF8 so enforcing that as the encodings makes the most sense. 

Reading that PEP, it seems they are speaking right to me:

> Additionally, many Python developers using Unix forget that the default encoding is platform dependent. They omit to specify encoding="utf-8" when they read text files encoded in UTF-8 (e.g. JSON, TOML, Markdown, and Python source files). Inconsistent default encoding causes many bugs.

I'll be honest, I did think it was default and hence I omitted it from `open`. I guess I failed at "explicit is better than implicit"

I can try to fix this later today or you can feel free to open a pull request. I am not sure how best to do a regression test though. I'll have to think on it or be okay with it missing.

**Comment by Jwink3101** [comment]
I am also interested in hearing more about how this runs on Windows. I wrote it trying to avoid assuming a platform but also without planned Windows support. Are there places where it needs some more development for windows? Are you using Windows directly or WSL? (Or whatever it's called now). I don't even have access to a windows machine on which to test.

**Comment by tonibony** [comment]
About fixing: I'm still not sure if adding that parameter is the better course of action. The Python developers are going to make the [UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode) default, right? And for now, maybe there is a way to turn that mode automatically, on syncrlone startup? If not, you can even add a paragraph in the Readme, instructing users on Windows (and other platforms with legacy system encoding) how to turn it on manually.

About usage on Windows: Currently, I am testing syncrclone directly on Windows 10, without WSL or any intermediate layer. Until now, this issue was the only significant obstacle. I'll write if I find something more 😉 

Note: I am using rclone (also on Windows) for about two years. Also, I am using FreeFileSync for so long, that I can't remember when I started (10+ years?). I also tested `rclone bisync`, it worked flawlessly on Windows. But for me your algorithm and whole approach are much better, very close to what I need and very similar to what I use from FreeFileSync.

**Comment by Jwink3101** [comment]
Glad it's working on Windows. I am honestly kind of surprised. Also glad you like the tool. I wrote it because I was not happy with how rclonesyncV2 worked (which is the tool used to mkae bisync). I had hacked rclone support into my other tool, [PyFiSync](https://github.com/Jwink3101/PyFiSync) and didn't love how it (a) couldn't do two non-local remotes (not that I have a real use for for that but still) and (b) needed ModTime.

Furthermore, as I read more and more of what @ncw explained in the forums about how rclone worked, it was clear that rclonesyncV2 (and bisync) fundamentally worked differently. You need state for bi-directional sync but I like using it as little as possible as opposed to it being in the critical path. (to be fair, syncrclone obviously breaks from how rclone works in many, if not more, other ways). I have written two prior sync tools (see [PBrsync](https://github.com/Jwink3101/PBrsync)) so I also had some (painful) lessons learned. And, to be fair, I am a control freak who has some extra pandemic time. 

Re encoding. I am still leaning towards changing it. Explicit is better and until I require that version of python (unlikely), I don't want to assume it. But I may just add a note in the mean time.

**Comment by Andrei-Olive1ra** [comment]
I had a similar problem and to solve it I just changed the "\" by "/" in the local directory path and it worked. Congratulations on the work Jwink3101!

**Comment by Andrei-Olive1ra** [comment]
> I got the following error (and similar) while syncrclone was reading the file lists (initially the lists generated by rclone and then the saved lists from previous run):
> 
> `ERROR: 'charmap' codec can't decode byte 0x98 in position 63910: character maps to <undefined>`
> 
> I investigated the problem and found the reason - it's combination of the following:
> 
> * Synced files have non-ASCII characters in their names (cyrillic in my case).
> * The platform (Windows, in my case) "uses legacy encodings for the system encoding (the ANSI Code Page). Python uses it for the default encoding of text files" (I am citing Python's documentation [Using Python on Windows](https://docs.python.org/3/using/windows.html)).
> * Syncrclone opens text files without specifying file's encoding (which should be utf-8) and that's somewhat problematic in current versions of Python - see [PEP 597 – Add optional EncodingWarning](https://peps.python.org/pep-0597/).
> 
> These findings led me to a successful workaround of the problem - I forced Python in [UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode) by setting the environment variable `PYTHONUTF8=1`.
> 
> Now, I know that syncrclone can be patched to fix this problem, by adding the optional parameter `encoding="utf-8"` to the relevant `open(...)` calls (because I tried that too). But I'm not sure if that's the right thing to do. It looks like the problem will be solved in the upcoming Python versions (3.15, as planned) - see [PEP 686 – Make UTF-8 mode default](https://peps.python.org/pep-0686/).

I had a similar problem and to solve it I just changed the "\" by "/" in the local directory path and it worked. Congratulations on the work Jwink3101!

**Comment by Jwink3101** [comment]
Can you elaborate on your problem and fix? I am not sure I follow and it doesn't make sense from the other issues. I would like to fix it if I it's systematic.

**Comment by Andrei-Olive1ra** [comment]
I'm a basic user and when I first tried to use syncrclone on Windows I got this error:

```
ERROR. Dumping logs (with debug) to 'None/log.txt'
Traceback (most recent call last):
  File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Lib\site-packages\syncrclone\cli.py", line 360, in cli
    config.parse(
  File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Lib\site-packages\syncrclone\cli.py", line 91, in parse
    exec(override + "\n\n" + text + "\n\n" + override, self._config)
  File "<string>", line 3
    remoteA = "C:\Users\Andrei\.logseq\Logseq"
                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Scripts\syncrclone-script.py", line 33, in <module>
    sys.exit(load_entry_point('syncrclone==20230310.0b0', 'console_scripts', 'syncrclone')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Lib\site-packages\syncrclone\cli.py", line 407, in cli
    with open(f"{tmpdir}/log.txt", "wt") as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None/log.txt'
``` 
From what I understood about this error I researched a solution to solve it, first I got here, but I didn't understand tonybony's solution. But knowing that it was something related to decoding, I found an answer on the internet, where it reported on a python problem of not understanding "\" .

I don't know if it's a python problem really, but changing "\" to "/" everything worked (remoteA = C:\Users\Andrei\.logseq\Logseq --> remoteA = C:/Users/Andrei/.logseq/ logseq).

Sorry if I wasn't clear in my explanation, my native language is Portuguese and I'm using Google Translator.

**Comment by Jwink3101** [comment]
> I'm a basic user and when I first tried to use syncrclone on Windows I got this error:
> 
> 
> 
> ```
> 
> ERROR. Dumping logs (with debug) to 'None/log.txt'
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Lib\site-packages\syncrclone\cli.py", line 360, in cli
> 
>     config.parse(
> 
>   File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Lib\site-packages\syncrclone\cli.py", line 91, in parse
> 
>     exec(override + "\n\n" + text + "\n\n" + override, self._config)
> 
>   File "<string>", line 3
> 
>     remoteA = "C:\Users\Andrei\.logseq\Logseq"
> 
>                                               ^
> 
> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Scripts\syncrclone-script.py", line 33, in <module>
> 
>     sys.exit(load_entry_point('syncrclone==20230310.0b0', 'console_scripts', 'syncrclone')())
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Andrei\AppData\Local\Programs\Python\Python311\Lib\site-packages\syncrclone\cli.py", line 407, in cli
> 
>     with open(f"{tmpdir}/log.txt", "wt") as fout:
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'None/log.txt'
> 
> ``` 
> 
> From what I understood about this error I researched a solution to solve it, first I got here, but I didn't understand tonybony's solution. But knowing that it was something related to decoding, I found an answer on the internet, where it reported on a python problem of not understanding "\" .
> 
> 
> 
> I don't know if it's a python problem really, but changing "\" to "/" everything worked (remoteA = C:\Users\Andrei\.logseq\Logseq --> remoteA = C:/Users/Andrei/.logseq/ logseq).
> 
> 
> 
> Sorry if I wasn't clear in my explanation, my native language is Portuguese and I'm using Google Translator.
> 
> 

I don't think this is related. Rclone can be weird about paths on windows from my reading. (No personal experience). And doubly unsure how that works with Python calling it. 

But I could be wrong. If there are other windows issues, please open a ticket. I don't use it but given that it takes very very thing to support it, I am happy to try.

**Comment by Jwink3101** [comment]
@Andrei-Olive1ra , are you still having this problem and/or have interest? If not, I will close it.
