### ISSUE TITLE
syncrclone in termux (Android): "Failed to rc: loopback..."

### ISSUE THREAD

**Issue by mcastillof** [Jwink3101/syncrclone#31]
cat /data/data/com.termux/files/usr/tmp/tmp6jhvm7pn/log.txt
```
2024-01-17 22:01:42: DEBUG: argv: ['config.py']
2024-01-17 22:01:42: DEBUG: CLI config: Namespace(configpath='config.py', break_lock=None, debug=False, dry_run=False, interactive=False, new=False, no_backup=False, override=[], reset_state=False)
2024-01-17 22:01:42: DEBUG: Localmode: False
2024-01-17 22:01:42: syncrclone (20231117.0.BETA)
2024-01-17 22:01:42: config path: 'config.py'
2024-01-17 22:01:42: temp dir: '/data/data/com.termux/files/usr/tmp/tmp6jhvm7pn'
2024-01-17 22:01:42: A: 'orgNotes:/'
2024-01-17 22:01:42: B: '/data/data/com.termux/files/home/storage/shared/rclone/Notes'
2024-01-17 22:01:42: DEBUG: config: Config(os=<module 'os' (frozen)>, subprocess=<module 'subprocess' from '/data/data/com.termux/files/usr/lib/python3.11/subprocess.py'>, hashlib=<module 'hashlib' from '/data/data/com.termux/files/usr/lib/python3.11/hashlib.py'>, time=<module 'time' (built-in)>, remoteA='orgNotes:/', remoteB='/data/data/com.termux/files/home/storage/shared/rclone/Notes', workdirA='orgNotes:.syncrclone', workdirB='/data/data/com.termux/files/home/storage/shared/rclone/Notes/.syncrclone', name='w9htW7c6ddefeacae12e3c76570856f9cdc17', rclone_exe='rclone', filter_flags=[], rclone_flags=[], rclone_env={}, rclone_flagsA=[], rclone_flagsB=[], compare='mtime', dt=1.1, conflict_mode='newer', tag_conflict=False, reuse_hashesA=False, reuse_hashesB=False, always_get_mtime=True, backup=True, backup_with_copy=None, sync_backups=False, hash_fail_fallback=None, set_lock=False, action_threads=1, cleanup_empty_dirsA=None, cleanup_empty_dirsB=None, avoid_relist=True, renamesA=None, renamesB=None, list_status_dt=10, save_logs=True, local_log_dest='', pre_sync_shell='', post_sync_shell='', stop_on_shell_error=False, tempdir='/data/data/com.termux/files/usr/tmp/tmp6jhvm7pn', configpath='config.py', break_lock=None, debug=False, dry_run=False, interactive=False, new=False, override=[], reset_state=False, workdir0A=None, workdir0B=None)
2024-01-17 22:01:42: rclone version:
2024-01-17 22:01:42: DEBUG: rclone:call ['rclone', 'rc', '--loopback', 'core/version']
2024-01-17 22:01:42: DEBUG: rclone: env {'RCLONE_ASK_PASSWORD': 'false'}
2024-01-17 22:01:42: rclone: {
2024-01-17 22:01:42: rclone: 	"error": "loopback: call failed: strconv.ParseInt: parsing \"\": invalid syntax",
2024-01-17 22:01:42: rclone: 	"path": "core/version",
2024-01-17 22:01:42: rclone: 	"status": 500
2024-01-17 22:01:42: rclone: }
2024-01-17 22:01:42: rclone: 2024/01/18 01:01:42 Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax
2024-01-17 22:01:42: RCLONE ERROR
2024-01-17 22:01:42: CMD ['rclone', 'rc', '--loopback', 'core/version']
2024-01-17 22:01:42: STDOUT and STDERR {
2024-01-17 22:01:42: 	"error": "loopback: call failed: strconv.ParseInt: parsing \"\": invalid syntax",
2024-01-17 22:01:42: 	"path": "core/version",
2024-01-17 22:01:42: 	"status": 500
2024-01-17 22:01:42: }
2024-01-17 22:01:42: 2024/01/18 01:01:42 Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax

```

rclone --version
```
rclone 1.65.1-termux
- os/version: unknown
- os/kernel: 4.14.326-lineageos+ (aarch64)
- os/type: android
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.21.5
- go/linking: dynamic
- go/tags: noselfupdate

```

**Comment by Jwink3101** [comment]
This is almost certainly something with Termux. `strconv.ParseInt` is not Python at all.

This isn't a critical part of the code. I could easily cut it out but it is indicative of a larger problem. 

Unfortunately, I don't use Android so I can't test it. 

Try the following in the terminal:

    rclone rc --loopback core/version

Then in a Python REPL, do the following (on mobile but this should be right)

    >>>> import subprocess,json
    >>>> cmd = ['rclone', 'rc', '--loopback', 'core/version']
    >>>> json.loads(subprocess.check_output(cmd))

What does that do?

**Comment by mcastillof** [comment]
In termux terminal:

```
~ $ rclone rc --loopback core/version
{
"error": "loopback: call failed: strconv.ParseInt: parsing \"\": invalid syntax",
"path": "core/version",
"status": 500
}
2024/01/18 09:13:05 Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax
```


And in Pytohn REPL (inside termux):

```
>> import subprocess,json
>> cmd = ['rclone', 'rc', '--loopback', 'core/version']
>> json.loads(subprocess.check_output(cmd))

2024/01/18 09:10:23 Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 466, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rclone', 'rc', '--loopback', 'core/version']' returned non-zero exit status 1.
```

**Comment by mcastillof** [comment]
I have commented out the line self.version_check() in __init__() in rclone.py

I'm able to sync my remote folder now. Thanks.

**Comment by Jwink3101** [comment]
> I have commented out the line self.version_check() in __init__() in rclone.py

Obviously, nobody can stop you but you've swept a problem under the rug and are taking a risk that (a) a future syncrclone update will almost certainly break (since I plan to move to the rc interface eventually or a newer rclone feature), and/or (b) the *current* version will also fail somewhere since there is some underlying bug in rclone and/or termux.

----

The fact that `rclone rc --loopback core/version` failed and that strconv.ParseInt is a golang construct (according to a quick search), there is likley a bug in the termux version of rclone. Has @ncw seen this?

**Comment by mcastillof** [comment]
I enabled back self.version_check() in _ _ init _ _ () in rclone.py of syncrclone and I have built rclone inside termux. First I tried to build it with the termux-package tools, but it failed. Then I followed [this instructions](https://github.com/rclone/rclone/wiki/rclone-on-Android-with-Termux) to get it to build in Android. The instructions are a bit outdated, I had to use 

`go install  github.com/rclone/rclone`

instead of 
`go get -u -v github.com/ncw/rclone`

After that, the error "Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax" went away:

```
~ $ syncrclone config.py 
2024-01-18 13:59:38: syncrclone (20231117.0.BETA)
2024-01-18 13:59:38: config path: 'config.py'
2024-01-18 13:59:38: temp dir: '/data/data/com.termux/files/usr/tmp/tmpjpwntxzl'
2024-01-18 13:59:38: A: 'orgNotes:/'
2024-01-18 13:59:38: B: '/data/data/com.termux/files/home/storage/shared/rclone/Notes'
2024-01-18 13:59:38: rclone version:
2024-01-18 13:59:38: rclone: {
2024-01-18 13:59:38: rclone: 	"arch": "arm64",
2024-01-18 13:59:38: rclone: 	"decomposed": [
2024-01-18 13:59:38: rclone: 		1,
2024-01-18 13:59:38: rclone: 		65,
2024-01-18 13:59:38: rclone: 		1
2024-01-18 13:59:38: rclone: 	],
2024-01-18 13:59:38: rclone: 	"goTags": "none",
2024-01-18 13:59:38: rclone: 	"goVersion": "go1.21.6",
2024-01-18 13:59:38: rclone: 	"isBeta": true,
2024-01-18 13:59:38: rclone: 	"isGit": true,
2024-01-18 13:59:38: rclone: 	"linking": "dynamic",
2024-01-18 13:59:38: rclone: 	"os": "android",
2024-01-18 13:59:38: rclone: 	"version": "v1.65.1-DEV"
2024-01-18 13:59:38: rclone: }
2024-01-18 13:59:38: 
...
```

**Comment by Jwink3101** [comment]
Great! That certainly tracks with what I guessed. Glad it's working. I am curious how it does in general on Android

**Comment by Jwink3101** [comment]
Closing

**Comment by ncw** [comment]
@mcastillof thanks for fixing the wiki :-)


```
~ $ rclone rc --loopback core/version
{
"error": "loopback: call failed: strconv.ParseInt: parsing \"\": invalid syntax",
"path": "core/version",
"status": 500
}
2024/01/18 09:13:05 Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax
```

This is indicative that the version that rclone was compiled with is not being understood by rclone!

The verson `1.65.1-termux` isn't being parsed properly. I think it probably would parse properly if it started with a `v`.

```
$ go build -v --ldflags "-s -X github.com/rclone/rclone/fs.Version=1.65.1-termux"
github.com/rclone/rclone

$ ./rclone version
rclone 1.65.1-termux
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-91-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.1
- go/linking: dynamic
- go/tags: none

$ ./rclone rc --loopback core/version
{
	"error": "loopback: call failed: strconv.ParseInt: parsing \"\": invalid syntax",
	"path": "core/version",
	"status": 500
}
2024/01/19 10:54:07 Failed to rc: loopback: call failed: strconv.ParseInt: parsing "": invalid syntax
```

With added `v`

```
$ go build -v --ldflags "-s -X github.com/rclone/rclone/fs.Version=v1.65.1-termux"
github.com/rclone/rclone

$ ./rclone version
rclone v1.65.1-termux
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-91-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.1
- go/linking: dynamic
- go/tags: none

$ ./rclone rc --loopback core/version
{
	"arch": "amd64",
	"decomposed": [
		1,
		65,
		1
	],
	"goTags": "none",
	"goVersion": "go1.20.1",
	"isBeta": true,
	"isGit": false,
	"linking": "dynamic",
	"os": "linux",
	"version": "v1.65.1-termux"
}
```

So if we could persuade the termux maintainer to put a `v` on the start of the version number it will work fine :-)

Can you make a termux issue @mcastillof ?

**Comment by mcastillof** [comment]
I have created the issue termux/termux-packages#19013 and created a [PR](https://github.com/termux/termux-packages/pull/19014). 

Thanks @Jwink3101, thanks @ncw. Have a good weekend!
